# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  CI: true
  # Overrides the Yarn and NPM cache directories so they are on the same drive as the source. This helps improve build performance on Windows hosted agents.
  YARN_CACHE_FOLDER: $(Build.SourcesDirectory)/../yarn-cache
  NPM_CONFIG_CACHE: $(Build.SourcesDirectory)/../npm-cache

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "azure@bot"
    git config --global user.name "Azure pipelines"
    git remote rm origin
    git remote add origin https://$GITHUB_TOKEN@github.com/Ramon92/bulma-web.git
    git fetch origin
    git checkout master 
  condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'checkout master'

- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'

- script: |
    yarn lerna publish --message 'chore: release new versions' --yes --registry "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'publish packages'

